---
title: Hyperion Gray's Chaotic Licensing Guide for the Aspiring Entrpreneur- Classic Edition, Hard-bound/Leather e-book.
date: Look at a clock.
---


remote_theme: jekyll/minima@d4d779a

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 


# GitHub Pages options
markdown: kramdown

# Optional: show in footer
author:
  name: "Hyperion Gray"
  email: "licenses@hyperiongray.local"

# Custom CSS
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings
  
# Include our custom assets
# include:
#  - assets/main.css
#  - HYPERION_GRAY_BOOK_ON_LICENSING_FOR_PEOPLE_WHO_CANT_READ_GOOD_AND_WANT_TO_LEARN_TO_DO_OTHER_STUFF_GOOD_TOO.md
#  - choose-your-license.md
#  - license-tarot.md
#  - LICENSE.WHGOSL.MD
#  - LICENSE.SHGODL.MD

# Optional: make URLs nice
permalink: pretty
